//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCargo
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CargoID { get; set; }
        public Nullable<double> CargoPrice { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Company Company { get; set; }
    }
}
