//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingLog
    {
        public int ID { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public string BagNumber { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> CargoID { get; set; }
        public string IntegrationType { get; set; }
        public string PaymentType { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public string UserName { get; set; }
        public string Explanation { get; set; }
        public Nullable<bool> Available { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
